
pool:
  vmImage: ubuntu-latest

steps:

- script: |

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'alushiro'
    projectKey: 'alushiro_springpet-clinic'
    projectName: 'springpet-clinic'
    scannerMode: 'Other'
  displayName: 'SonarCloud Prepare'
  
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false