
pool:
  vmImage: ubuntu-latest

steps:

- script: |
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Build
#- task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'SonarCloud'
#    organization: 'alushiro'
#    projectKey: 'alushiro_springpet-clinic'
#    projectName: 'springpet-clinic'
#  displayName: 'SonarCloud Prepare'
  
#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'sonarqube'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: true
#    sqGradlePluginVersionChoice: 'specify'
#    sonarQubeGradlePluginVersion: '3.5.0.2730'
#    spotBugsAnalysis: false